import { contributionAttestationPayload,contributionAttestationPayloadDigest,TREESEED_AGENT_CONTRIBUTION_ATTESTATION_VERSION,TREESEED_CONTRIBUTION_GRANT_VERSION,type AgentContributionAttestation,type ProjectContributionAuthorization } from '@treeseed/sdk/work-providers';
import { describe,expect,it } from 'vitest';
import { prepareProjectContributionAttestation } from '../../../src/agents/contributions/project-contribution-attestation.ts';

async function bundle(){const pair=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']);const publicKeyJwk=await crypto.subtle.exportKey('jwk',pair.publicKey);const authorization:ProjectContributionAuthorization={schemaVersion:TREESEED_CONTRIBUTION_GRANT_VERSION,id:'grant-1',generation:1,status:'active',projectId:'project-1',repository:{provider:'github',owner:'treeseed-ai',name:'agent'},grant:{version:'v1',digest:'sha256:grant'},receiptKey:{keyId:'key-1',algorithm:'Ed25519',publicKeyJwk},authorizedBy:{principalId:'human-1'},agentIds:['agent-1'],capacityProviderIds:['provider-1'],contributionModes:['agent-authored'],targetBranches:['staging'],allowedActions:['populate_pr_attestation'],effectiveAt:'2026-08-20T12:00:00.000Z',expiresAt:'2027-08-20T12:00:00.000Z'};const attestation:AgentContributionAttestation={schemaVersion:TREESEED_AGENT_CONTRIBUTION_ATTESTATION_VERSION,authorization:{id:'grant-1',generation:1,digest:'sha256:grant'},projectId:'project-1',repository:authorization.repository,assignmentId:'assignment-1',agentId:'agent-1',capacityProviderId:'provider-1',mode:'agent-authored',base:{branch:'staging',sha:'a'.repeat(40)},head:{branch:'codex/assignment-1',sha:'b'.repeat(40)},issuedAt:'2026-08-20T13:00:00.000Z',receipt:{keyId:'key-1',algorithm:'Ed25519',payloadDigest:'pending',signature:'pending'}};attestation.receipt.payloadDigest=await contributionAttestationPayloadDigest(attestation);attestation.receipt.signature=Buffer.from(await crypto.subtle.sign('Ed25519',pair.privateKey,contributionAttestationPayload(attestation))).toString('base64url');return{authorization,attestation};}
const input=()=>({permission:{mode:'delegated-project-authorization' as const,mayPopulatePrAttestation:true,requiredCapability:'contribution_attestation' as const,requireExactHead:true as const},availableCapabilities:['contribution_attestation'],projectId:'project-1',assignmentId:'assignment-1',agentId:'agent-1',capacityProviderId:'provider-1',mode:'agent-authored' as const,repository:{provider:'github',owner:'treeseed-ai',name:'agent'},base:{branch:'staging',sha:'a'.repeat(40)},head:{branch:'codex/assignment-1',sha:'b'.repeat(40)}});
describe('agent contribution attestation',()=>{
	it('requests, verifies, and renders only an API-signed exact-head bundle',async()=>{const value=await bundle();const result=await prepareProjectContributionAttestation({...input(),client:{request:async()=>({ok:true,payload:value})}});expect(result.ok).toBe(true);if(result.ok)expect(result.managedBodyBlock).toContain('treeseed:contribution-attestation:start');});
	it('fails before API access without explicit capability',async()=>{let calls=0;const result=await prepareProjectContributionAttestation({...input(),availableCapabilities:[],client:{request:async()=>{calls+=1;return{};}}});expect(result).toEqual({ok:false,code:'contribution_attestation_capability_missing'});expect(calls).toBe(0);});
});
